# Copyright Contributors to the Open Cluster Management project

sudo: required
addons:
  apt:
    packages:
    - git
    - make
    - curl
env:
  - DOCKER_IMAGE_NAME=cloudposse/#####################
services:
- docker
install:
- make init
- make travis/docker-login

script:
- make docker/build

after_success:
- make travis/docker-tag-and-push
